from prompt.prediction_prompts import RUN_PREDICTION_INPUT, RUN_PREDICTION_OUTPUT, RUN_PREDICTION_INPUT_COT, RUN_PREDICTION_OUTPUT_COT

__all__ = [
    "RUN_PREDICTION_INPUT",
    "RUN_PREDICTION_OUTPUT",
    "RUN_PREDICTION_INPUT_COT",
    "RUN_PREDICTION_OUTPUT_COT",
]